project_id = "cemxunknyvqvzudrxwih"

[functions.admin-users]
verify_jwt = true

[functions.admin-companies]
verify_jwt = true

[functions.bootstrap-super-admin]
verify_jwt = false

[functions.billing]
verify_jwt = false
